version: '3.7'

services:
  app-server:
    build:
      context: ./weatherapp-backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - weather-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://weather-mysql:3306/weatherapp?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: weatherapp
      SPRING_DATASOURCE_PASSWORD: weatherapp     
    networks:
      - backend
      - frontend

  app-client:
    build:
      context: ./weatherapp/
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  

  weather-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: weatherapp
      MYSQL_USER: weatherapp
      MYSQL_PASSWORD: weatherapp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend  

volumes:
  mysql-data:

networks:
  backend:
  frontend: